Task D review
valeriy-zainullin/algorithms-review pull request #1
Opened 2023-03-24 21:45 UTC by valeriy-zainullin

2023-04-09 03:33 UTC, RickMortey requested changes
Readability improvement required.

2023-04-09 03:33 UTC, RickMortey commented on D.cpp
> +			assert(rightmost_z_block_end == i - 1);
смотри коммент про ассерты из таски А

2023-04-09 03:33 UTC, RickMortey commented on D.cpp
> +
Константы всегда в отдельный неймспейс

2023-04-09 03:33 UTC, RickMortey commented on D.cpp
> +		// printf("target_word_pos = %zu, z_func[pos] = %zu, dp_can_partition_suffix_at[pos] = %u, dp_next_suffix_start[pos] = %zu, last_partitionable_suffix_start = %zu.\n", pos - source_word.size(), z_fu
Если не нужно, удаляй.

2023-04-09 03:33 UTC, RickMortey commented on D.cpp
> +	std::string target_word(k_buffer);
Все еще не понимаю, за что так хейтишь cin

2023-04-09 03:33 UTC, RickMortey commented on D.cpp
> +	std::string target_word(k_buffer);
В целом выглядит как C-style код, такого лучше избегать. Пишем на плюсах как-никак.

2023-04-09 03:33 UTC, RickMortey commented on D.cpp
> +}
Очень трудно читать код. Подумай, можно ли как-нибудь улучшить читаемость.

2023-05-08 23:46 UTC, valeriy-zainullin commented on D.cpp
> +	std::string target_word(k_buffer);
Это более удобно для олимпиадного программирования, поскольку не удобно работать с вещественными числами в iostream. fixed, setprecision нужно писать на каждое число, не удобно. И длинно. Но это не наш случай, давайте исправлю.

2023-05-12 17:11 UTC, RickMortey commented on D.cpp
> +	std::string target_word(k_buffer);
Да, спасибо за исправление. Основная мысль ревью заключается в том, чтобы писать более "промышленный код", под которым понимается лучшая читаемость, т.к. перечитывать код и его дорабатывать придётся часто в проме.
И получается палка о двух концах, где на одном конце эффективность, на другом читаемость и нужно найти баланс.

2023-05-12 17:13 UTC, RickMortey commented
Ты вроде писал комменты в тредах, но нет исправлений. Мб ты закоммитил в другую ветку? Можешь в эту закоммитить, чтобы можно было увидеть разницу?

2023-05-15 17:36 UTC, valeriy-zainullin commented
> Ты вроде писал комменты в тредах, но нет исправлений. Мб ты закоммитил в другую ветку? Можешь в эту закоммитить, чтобы можно было увидеть разницу?

Не, я исправил, но забыл закоммитить. Сейчас буду быстренько отвечать на ревью, времени мало. Плохо, что я задержал.

2023-05-15 23:39 UTC, valeriy-zainullin commented on D.cpp
> +			assert(rightmost_z_block_end == i - 1);
Исправил, посмотрите. Извините за задержки.

2023-05-15 23:48 UTC, valeriy-zainullin commented on D.cpp
> +
Заменил ввод-вывод на iostream, константы ушли.

2023-05-15 23:50 UTC, valeriy-zainullin commented on D.cpp
> +		// printf("target_word_pos = %zu, z_func[pos] = %zu, dp_can_partition_suffix_at[pos] = %u, dp_next_suffix_start[pos] = %zu, last_partitionable_suffix_start = %zu.\n", pos - source_word.size(), z_fu
Удалено. Посмотрите.

2023-05-15 23:50 UTC, valeriy-zainullin commented on D.cpp
> +	std::string target_word(k_buffer);
Закоммитил.

2023-05-15 23:52 UTC, valeriy-zainullin commented on D.cpp
> +}
А в каком смысле сложно читать? Вроде как, переменные говорящие. Мб не очевидно, что динамическое программирование делает, `while (true)` стоит убрать? Или объяснить, что мы хотим добиться с помощью `joined`?

2023-05-18 23:17 UTC, merged