Task A review
valeriy-zainullin/algorithms-review pull request #2
Opened 2023-03-24 21:48 UTC by valeriy-zainullin

@RickMortey (не знаю, как по-другому добавить в reviewers..)

2023-04-09 03:22 UTC, RickMortey requested changes

2023-04-09 03:22 UTC, RickMortey commented on A.cpp
> +		//   Just now analyse some examples with such a picture.
Такую длинную пасту по-хорошему бы вынести в другое место. Например, перед объявлением функции.

2023-04-09 03:22 UTC, RickMortey commented on A.cpp
> +	assert(pattern.find('#') == std::string_view::npos); // std::string_view::contains and std::string::contains from c++23 onwards, wanted to use pattern.contains().
Круто, что делаешь проверку, но если она валится, она должна выводить что-то осмысленное.
Рекомендую написать функцию, которая позволяет делать assert-ы со своим выводом.
Такой ассерт не будет котироваться: assert(a == b && "A is not equal to B");

2023-04-09 03:22 UTC, RickMortey commented on A.cpp
> +	static const char * const kFormatStr = "%50000s";
Константы всегда в отдельный неймспейс.

2023-04-09 03:22 UTC, RickMortey commented on A.cpp
> +	std::string pattern(buffer.get());
Честно говоря, не понял зачем так делать.

2023-05-08 23:28 UTC, valeriy-zainullin commented on A.cpp
> +		//   Just now analyse some examples with such a picture.
Исправил, посмотрите

2023-05-08 23:36 UTC, valeriy-zainullin commented on A.cpp
> +	assert(pattern.find('#') == std::string_view::npos); // std::string_view::contains and std::string::contains from c++23 onwards, wanted to use pattern.contains().
Исправил, посмотрите.

2023-05-08 23:38 UTC, valeriy-zainullin commented on A.cpp
> +	static const char * const kFormatStr = "%50000s";
Исправил, посмотрите.

2023-05-08 23:39 UTC, valeriy-zainullin commented on A.cpp
> +	std::string pattern(buffer.get());
Зачем выделять буфер с помощью unique_ptr? Чтобы память не утекла. Или лучше заказать вектор? Если так лучше, исправлю.

2023-05-09 00:23 UTC, valeriy-zainullin commented on A.cpp
> +	std::string pattern(buffer.get());
Заменил ввод/вывод языка C на ввод/вывод C++.

2023-05-12 17:09 UTC, RickMortey commented
Всё круто!

2023-05-12 17:09 UTC, merged