Task I review
valeriy-zainullin/algorithms-review pull request #3
Opened 2023-03-24 21:49 UTC by valeriy-zainullin

Сегодня же исправлю на хеши.
@RickMortey

2023-04-09 03:49 UTC, RickMortey requested changes
Мне кажется, что структура StrHash лишняя и можно было обойтись классом StrHasher. В чём явная необходимость?

Очень трудно читать код из-за обилия закомменченного неиспользованного кода.

В целом про комментарии: комментарии -- это круто, но нужно помнить, что краткость -- сестра таланта. Также можно использовать doxygen для документирования классов и функций по единому стандарту: https://www.doxygen.nl/manual/docblocks.html

Оставь в мейне только ввод, вызов функций, решающих все проблемы, вывод.

2023-04-09 03:49 UTC, RickMortey commented on I.cpp
> +	static constexpr const uint32_t kMod2 = 1073676287;
Классовые константы в enum

2023-04-09 03:49 UTC, RickMortey commented on I.cpp
> +	static constexpr const char * const kStrFmt    = "%10s";
Константы всегда в отдельный неймспейс

2023-04-09 03:49 UTC, RickMortey commented
+ форматируй код с помощью clang по гугл кодстайлу

2023-05-16 00:00 UTC, valeriy-zainullin commented
> Мне кажется, что структура StrHash лишняя и можно было обойтись классом StrHasher. В чём явная необходимость?
> 
> Очень трудно читать код из-за обилия закомменченного неиспользованного кода.
> 
> В целом про комментарии: комментарии -- это круто, но нужно помнить, что краткость -- сестра таланта. Также можно использовать doxygen для документирования классов и функций по единому стандарту: https://www.doxygen.nl/manual/docblocks.html
> 
> Оставь в мейне только ввод, вызов функций, решающих все проблемы, вывод.

Хочется иметь возможность увеличивать пространство хешей, потому есть такая структура. Другое дело, что в задаче по времени не проходит без unordered_map. Т.е. это хеш-таблица хешей, чтобы прошло..

2023-05-16 00:00 UTC, valeriy-zainullin commented
Если стоит, уберу.

2023-05-18 23:21 UTC, RickMortey commented
`Хочется иметь возможность увеличивать пространство хешей, потому есть такая структура. Другое дело, что в задаче по времени не проходит без unordered_map. Т.е. это хеш-таблица хешей, чтобы прошло.. Если стоит, уберу.`

Понял, окей

2023-05-18 23:21 UTC, merged