Task M review
valeriy-zainullin/algorithms-review pull request #4
Opened 2023-03-24 21:49 UTC by valeriy-zainullin

@RickMortey

2023-04-09 03:59 UTC, RickMortey requested changes
Очень круто, что делаешь такие полные комменты, позволяющие отследить ход решения и используемые алгоритмы. Однако их изобилие может вредить читаемости кода. Иногда достаточно ссылки и описания того, что ты использовал. Если хочется полного описания -- используй doxygen.
(inline comments всё еще ок)

2023-04-09 03:59 UTC, RickMortey commented on M.cpp
> +	assert(!text.empty());
Ассерты должны быть с выводом, если они повалились. Сделай свою функцию ассерта.

2023-04-09 03:59 UTC, RickMortey commented on M.cpp
> +	constexpr char kTextEndChr = '\10';
Константы всегда в отдельный неймспейс.

2023-04-09 03:59 UTC, RickMortey commented on M.cpp
> +	constexpr char kSrcStrAlphabetMaxChr = 127; //'z';
неймспейс

2023-04-09 03:59 UTC, RickMortey commented on M.cpp
> +	*/
Если не нужно, удаляй.

Если нужно для тестинга, можешь сделать с помощью gtest/catch в отдельной сборке (e.g. #ifdef DEBUG)

2023-04-09 03:59 UTC, RickMortey commented on M.cpp
> +		*/
Сейм коммент

2023-04-09 03:59 UTC, RickMortey commented on M.cpp
> +	constexpr size_t kBufferSize = 4096;
Отдельный неймспейс

2023-04-10 20:23 UTC, RickMortey commented on M.cpp
> +	//   не совпадёт. Мб и раньше будет несовпадение.
Бтв базированно, что оставляешь комменты, но неиронично трудно читать, лучше ссылочку какую-нибудь вставить. Можешь оформить в техе/notion (хз, поддерживает ли он тех)

2023-05-18 23:23 UTC, RickMortey commented
Привет! Будешь допиливать или закрываем?

2023-05-21 04:19 UTC, valeriy-zainullin commented
Привет! Допиливать буду, допилю сегодня в течение двух часов.

2023-05-21 04:49 UTC, valeriy-zainullin commented on M.cpp
> +	assert(!text.empty());
Сделал, посмотрите.

2023-05-21 04:49 UTC, valeriy-zainullin commented on M.cpp
> +	constexpr char kTextEndChr = '\10';
Сделал, посмотрите, норм ли.

2023-05-21 04:49 UTC, valeriy-zainullin commented on M.cpp
> +	constexpr char kSrcStrAlphabetMaxChr = 127; //'z';
Сделал. И функцию поместил в то же пространство.

2023-05-21 04:49 UTC, valeriy-zainullin commented on M.cpp
> +	*/
Сделал как отладочный вывод в отдельной сборке, если будет включен макрос DEBUG.

2023-05-21 04:50 UTC, valeriy-zainullin commented on M.cpp
> +		*/
Теперь собирается, но только в сборке с макросом DEBUG.

2023-05-21 04:51 UTC, valeriy-zainullin commented on M.cpp
> +	constexpr size_t kBufferSize = 4096;
Исправил. Посмотрите.

2023-05-21 04:52 UTC, valeriy-zainullin commented on M.cpp
> +	//   не совпадёт. Мб и раньше будет несовпадение.
Привел в чувство этот участок)

2023-05-21 04:52 UTC, valeriy-zainullin commented on M.cpp
> +	//   не совпадёт. Мб и раньше будет несовпадение.
Всё вынес в отдельный файл с замечаниями. Если человеку придется разбираться, сможет обратится к нему. А в противном случае будет по существу реализация с замечаниями по ней.

2023-05-21 04:53 UTC, valeriy-zainullin commented
Привел в чувство немного, действительно, если человек уже знает реализацию, будет проще работать. Посмотри теперь, что ещё осталось исправить.

2023-05-22 20:05 UTC, RickMortey approved these changes
Все норм!

2023-05-22 20:06 UTC, merged