Publish F.
valeriy-zainullin/algorithms-review pull request #5
Opened 2023-04-24 14:56 UTC by valeriy-zainullin

Здравствуйте.

2023-05-19 00:01 UTC, RickMortey requested changes
Для юзабилити комменты на англе будут лучше. Желательно, но необязательно
Нужно для функций писать doxygen
Не забудь пасту вынести в отдельную ссылчоку (ее можно оставить на русском)

2023-05-19 00:01 UTC, RickMortey commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
Давай это уберем в ссылочку

2023-05-21 03:54 UTC, valeriy-zainullin commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
Да, сделаю отдельный файл, на него буду ссылаться. Хорошая идея! Просто на работе очень не хватает комментов по делу, что происходит, приходится тратить время. Хотя можно и спросить у того, кто писал, если он ещё работает.

2023-05-21 04:10 UTC, valeriy-zainullin commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
Сделал. Посмотрите.

2023-05-21 04:13 UTC, valeriy-zainullin commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
Да, хотел сейчас переделать на английский, но очень много переделывать. Думаю, оставлю. Если бы это было в рабочем коде, в будущем перевел бы на английский.

2023-05-21 04:13 UTC, valeriy-zainullin commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
Doxygen напишу.

2023-05-21 04:18 UTC, valeriy-zainullin commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
Написал doxygen к функции подсчёта простых (она только одна в глобальной области видимости).

2023-05-22 20:50 UTC, RickMortey commented on F.cpp
> +	// В общем, получается O(n^(2 / 3) (log(n))^(1 / 3)).
> Да, сделаю отдельный файл, на него буду ссылаться. Хорошая идея! Просто на работе очень не хватает комментов по делу, что происходит, приходится тратить время. Хотя можно и спросить у того, кто писал, если он ещё работает.


Вот кстати с этим очень помогает вики как будто-бы. Можно там создать страничку и туда ссылаться, например. Учитывая, сколько всего прикольно в вики от конфлюенса есть, мне кажется это норм тема)

2023-05-22 20:51 UTC, merged