Task H review
valeriy-zainullin/algorithms-review pull request #6
Opened 2023-04-24 15:00 UTC by valeriy-zainullin

@RickMortey
Здравствуйте. Уже прочитал замечания по некоторым из прошлых задач, но пока не успел исправить. Исправлю всё сразу. Если замечание повторяется, пожалуйста, проигнорируйте, исправлю, или отреагируйте просто одним словом.

2023-05-19 00:06 UTC, RickMortey requested changes
В целом все норм, но есть пара замечаний, см комменты.

2023-05-19 00:06 UTC, RickMortey commented on H.cpp
> +*/
Сейм коммент про пасты как из таски F

2023-05-19 00:06 UTC, RickMortey commented on H.cpp
> +	double im_;
Для класса и конструктора нужен doxygen, остальное это гипердушно так как всё понятно, так что оставь как есть сейчас

2023-05-19 00:06 UTC, RickMortey commented on H.cpp
> +	static const int kReverse  = 1;
Можно и в enum кажется

2023-05-19 00:06 UTC, RickMortey commented on H.cpp
> +	std::reverse(product.begin(), product.end());
Как будто бы конечному пользователю не очень хочется что-то делать с массивами перед тем, как их засунуть в функцию

2023-05-21 03:27 UTC, valeriy-zainullin commented on H.cpp
> +*/
Да, понимаю. Если бы это было на работе, можно было бы хранить рядом с кодом, в отдельном файле, а здесь оставить ссылку. Потому что хорошо, когда авторы оставляют объяснение того, что происходит. Не всегда так в реальных продуктах делают, конечно, потом ничего не понятно. Вынесу в отдельный файл, оставлю ссылку.

2023-05-21 03:27 UTC, valeriy-zainullin commented on H.cpp
> +	double im_;
Ок, сделаю

2023-05-21 03:27 UTC, valeriy-zainullin commented on H.cpp
> +	static const int kReverse  = 1;
Правда. Сделаю.

2023-05-21 03:29 UTC, valeriy-zainullin commented on H.cpp
> +	std::reverse(product.begin(), product.end());
Да, есть перемножение многочленов, которое ожидает, что номер в массиве соответствует степени коэффициента. Давайте вынесем это в функцию для решения нашей задачи, а функцию для перемножения оставим. Сделаю.

2023-05-21 03:32 UTC, valeriy-zainullin commented on H.cpp
> +*/
Хотя эту пасту я не дописал, конечно)

2023-05-21 03:34 UTC, valeriy-zainullin commented on H.cpp
> +*/
Убрал. Посмотрите.

2023-05-21 03:44 UTC, valeriy-zainullin commented on H.cpp
> +	double im_;
Готово. Посмотрите.

2023-05-21 03:48 UTC, valeriy-zainullin commented on H.cpp
> +	static const int kReverse  = 1;
Сделал. Посмотрите.

2023-05-21 03:53 UTC, valeriy-zainullin commented on H.cpp
> +	std::reverse(product.begin(), product.end());
Готово. Посмотрите.

2023-05-22 20:59 UTC, RickMortey approved these changes
ОК!

2023-05-22 20:59 UTC, merged