Task B review.
valeriy-zainullin/algorithms-review pull request #7
Opened 2023-05-16 03:14 UTC by valeriy-zainullin

Ещё не всё исправил из того, что говорили по прошлым задачам. Сделаю.

2023-05-22 21:05 UTC, RickMortey requested changes

2023-05-22 21:05 UTC, RickMortey commented on B.cpp
> +		  	return p1_distsq < p2_distsq;
ну как будто бы это хочется вынести в отдельный компаратор

2023-05-22 21:05 UTC, RickMortey commented on B.cpp
> +	}
Сделай перегрузку ввода вывода для point и делай через cin cout, намного приятнее имхо.

2023-05-24 05:07 UTC, valeriy-zainullin commented on B.cpp
> +		  	return p1_distsq < p2_distsq;
Сделал, посмотрите.

2023-05-24 05:13 UTC, valeriy-zainullin commented on B.cpp
> +	}
Сделал. Посмотрите.

2023-05-24 17:21 UTC, RickMortey approved these changes
Readability has been actually improved. Approved!

2023-05-24 17:21 UTC, merged